### ISSUE TITLE
Падает с "The operation completed successfully"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ViPetroFF/zcahttpproxy#14]
```
What steps will reproduce the problem?
1. Пока не понятно что надо сделать в 
операционной системе для получения такой 
ошибки.
2. Падает при запуске программы.

What is the expected output? What do you see instead?

А падает с:
Unhandled Exception: System.ComponentModel.Win32Exception: The operation 
completed successfully
   at LibVLCPlugin.LibVLCModule.LibVLCModuleInit(String strInitParamCAPlugin, String[] args, IPAddress MCastIPAddr, Int3
2 iCAPort) in d:\Projects\ZCaHttpProxy\LibVLCPlugin\LibVLCModule.cs:line 101
   at LibVLCPlugin.LibVLCModule..ctor(String strConfigPath, String strCaUri, IPAddress MCastIPAddr) in d:\Projects\ZCaHt
tpProxy\LibVLCPlugin\LibVLCModule.cs:line 59
   at ZCAHTTPProxy.CAHTTPProxy.Start(IPAddress mifaceIP)
   at ZCAHTTPProxy.CAHTTPProxy.Main(String[] args)

При этом предыдущая версия 1.2.2.1 
запускается без проблем.

Скорее всего ошибка связана с тем, что в 
текущей версии инициализация библиотеки 
LibVlc производится немного по-другому, 
нежели это было в версии 1.2.2.1. Но что 
вызывает ошибку инициализации доподлинно 
неизвестно. Как вариант исправления, в 
следующих версиях можно попробовать 
вернуться к тем параметрам инициализации, 
которые были в версии 1.2.2.1. Однако 
непонятен масштаб проблемы, какой процент 
пользователей столкнулись с данной 
ошибкой.

Баг заведён на базе комментария одного из 
пользователей, также были жалобы на форуме: 
http://forum.interzet.ru/index.php?showtopic=98004&view=findpost&p=935488


#2 oldpeepper
А исходники уже совсем устарели ?
Собственно, етот файл вываливает ту же 
ошибку, что и скомпилённый в выложенном 
виде проект. во аногих местах проблемы со 
сравнением возвращаемого указателя с 
IntPtr.Zero.
Например:
        private void CALibVLCHookInit(IPAddress MCastIPAddr, int iCAPort)
        {
            if (IntPtr.Zero != _hmodCALibVLCHook)
                throw new Win32Exception(1157);
            var procAddress = WINAPIImport.GetProcAddress(_hmodCALibVLCHook, "_CAServerAddressInit@8");
            if (IntPtr.Zero != procAddress)
                throw new Win32Exception(Marshal.GetLastWin32Error());
И т.п.
В лучшем случае:
            if (!(IntPtr.Zero != num))
                throw new Win32Exception(Marshal.GetLastWin32Error());
Работает в данном случае корректно, но явно 
код после дизассемблера.

А падает с:
Unhandled Exception: System.ComponentModel.Win32Exception: The operation 
completed successfully
   at LibVLCPlugin.LibVLCModule.LibVLCModuleInit(String strInitParamCAPlugin, String[] args, IPAddress MCastIPAddr, Int3
2 iCAPort) in d:\Projects\ZCaHttpProxy\LibVLCPlugin\LibVLCModule.cs:line 101
   at LibVLCPlugin.LibVLCModule..ctor(String strConfigPath, String strCaUri, IPAddress MCastIPAddr) in d:\Projects\ZCaHt
tpProxy\LibVLCPlugin\LibVLCModule.cs:line 59
   at ZCAHTTPProxy.CAHTTPProxy.Start(IPAddress mifaceIP)
   at ZCAHTTPProxy.CAHTTPProxy.Main(String[] args)

Собственно, из-за некорректной проверки на 
IntPtr.Zero.

Есть подозрения, что версии LibVlc разные, т.к. 
сигнатуры функций другие..
Нельзя ли выложить последние актуальные 
исходники вместе с использовавшимися 
версиями библиотек и компонентов ?
```

Original issue reported on code.google.com by `_vik...@bk.ru` on 5 Aug 2015 at 8:30

Attachments:
* [BAG.jpg](https://storage.googleapis.com/google-code-attachments/zcahttpproxy/issue-14/comment-0/BAG.jpg)

**Comment by ViPetroFF** [comment]
Версия 1.2.3.1 и 1.2.3.2.
Возможно в системе отсутствует файл "msvcr120.dll", на который ссылается "LibVLCHook.dll". Проверить это можно путём временного удаления файла LibVLCHook.dll, без него программа должна будет запуститься.

Fix: Необходимо установить Visual C++ Redistributable Packages for Visual Studio 2013.

TO DO: В исходном коде надо будет добавить "SetLastError = true", чтобы вместо 0 возвращался системный код ошибки. Это подсказка от Марка Сафонова.
`[DllImport("kernel32.dll", SetLastError = true)]`

Обычно появляется системное сообщение об отсутствии библиотеки "msvcr120.dll", как оказалось это происходит не всегда, на серверных версиях windows его не обнаружили.
![msvcr120](https://cloud.githubusercontent.com/assets/5168209/19091815/cd4d799e-8a8c-11e6-8c78-ae5c3b7e4111.png)
![msvcr120silent](https://cloud.githubusercontent.com/assets/5168209/19091935/450e42d8-8a8d-11e6-9e05-b49eaf01db5a.jpg)
